apiVersion: 2019-12-01
location: northeurope
name: SQLAppGroup
properties:
  containers: 
  - name: db
    properties:
      image: appregistry30022.azurecr.io/appsqlimage:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 3306
  - name: web
    properties:
      image: appregistry30022.azurecr.io/sqlapp:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 80          
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 80
  imageRegistryCredentials:
    - server: appregistry30022.azurecr.io
      username: appregistry30022
      password: VLy7gf1/sAUNQmqQ3nYWeDuPThdiqmIr
type: Microsoft.ContainerInstance/containerGroups